# TP9 - Spring Security Demo
spring.application.name=SpringSecurityDemo

# Port du serveur (optionnel, 8080 par défaut)
server.port=8081

# Désactiver le mot de passe généré automatiquement (on utilise notre config)
# spring.security.user.name=user
# spring.security.user.password=password

# Thymeleaf - rechargement des templates sans redémarrage (dev)
spring.thymeleaf.cache=false
